name: Push Share la Pointe 

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      action:
        description: "Action to perform (start/stop)"
        required: true
        type: choice
        options:
          - start
          - stop
      team_notification:
        description: "Send Teams notification"
        required: true
        type: boolean
        default: true
      desired_size:
        description: "Number of nodes when starting the cluster manually, (for schedule action we use a Github Action var: EKS_DESIRED_SIZE"
        required: false
        type: number
        default: 3
# Il n'y a plus de cluster ds ton compte AWS donc on suspend les job cron
  schedule:
    # Run at 04:00 UTC every day
    - cron: "0 4 * * *"

jobs:
  manage-cluster:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Display variables
        run: |
          echo "Target cluster name: ${{ vars.EKS_CLUSTER_NAME }}"
          echo "Target cluster node #: ${{ vars.EKS_DESIRED_SIZE }}"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Manage EKS Cluster
        run: |
          aws sts get-caller-identity
          ACTION="${{ github.event_name == 'schedule' && 'stop' || github.event.inputs.action }}"
          TEAM_NOTIFY="${{ github.event_name == 'schedule' && 'true' || github.event.inputs.team_notification }}"
          DESIRED_SIZE="${{ github.event_name == 'schedule' && vars.EKS_DESIRED_SIZE || github.event.inputs.desired_size }}"
          python eks_scaler/python/main.py ${{ vars.EKS_CLUSTER_NAME }} $ACTION --team-notify $TEAM_NOTIFY --desired-size $DESIRED_SIZE
