name: Upload to SharePoint via OIDC

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  SITE_ID: ${{ secrets.SITE_ID }}
  FILE_NAME: "demo.txt"
  LOCAL_PATH: "./demo.txt"

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create test file
        run: echo "Hello SharePoint from GitHub Actions" > ${{ env.FILE_NAME }}

      - name: Login to Azure with OIDC
        uses: azure/login@v1
        with:
          #client-id: "bfa3f3a0-b662-44f3-91d6-c9cdbbc29a3f" #GitHub-Sharepoint
          client-id: "d4f66394-2034-4bb8-aa40-7cb8d4f1c58a" #github-sharepoint-integration
          #client-id: ${{ secrets.AZURE_CLIENT_ID }}
          #tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          #subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

          tenant-id: "7264fb2a-5580-4c1e-a169-3df80f011601" #nbeaudoin456
          subscription-id: "c104e174-8f82-4e43-889c-d3b22b5da7b8" #SUB-1

      - name: Get Microsoft Graph access token
        id: get-token
        run: |
          TOKEN=$(az account get-access-token --resource=https://graph.microsoft.com --query accessToken -o tsv)
          echo "accessToken=$TOKEN" >> $GITHUB_OUTPUT

      - name: Debug Access Token (App ID utilisée)
        run: |
          echo "${{ steps.get-token.outputs.accessToken }}" | cut -d '.' -f2 | base64 -d | jq
        


      - name: Upload file to SharePoint (Graph API)
        run: |
          echo "Uploading file to SharePoint..."
          curl -v -X PUT \
            -H "Authorization: Bearer ${{ steps.get-token.outputs.accessToken }}" \
            -H "Content-Type: text/plain" \
            --upload-file "${{ env.LOCAL_PATH }}" \
            "https://graph.microsoft.com/v1.0/sites/${{ env.SITE_ID }}/drive/root:/${{ env.FILE_NAME }}:/content"

#      - name: Verify file upload
#        run: |
#          echo "Verifying file in SharePoint..."
#          curl -v -X GET \
#            -H "Authorization: Bearer ${{ steps.get-token.outputs.accessToken }}" \
#            -H "Content-Type: application/json" \
#            "https://graph.microsoft.com/v1.0/sites/${{ env.SITE_ID }}/drive/root:/${{ env.FILE_NAME }}"

#      - name: List files in Shared Documents
#        run: |
#          echo "Listing files..."
#          curl -v -X GET \
#            -H "Authorization: Bearer ${{ steps.get-token.outputs.accessToken }}" \
#            -H "Content-Type: application/json" \
#            "https://graph.microsoft.com/v1.0/sites/${{ env.SITE_ID }}/drive/root:/Shared%20Documents:/children"
          